### ISSUE TITLE
diacritical version of Wylie

### ISSUE THREAD

**Issue by eroux** [buda-base/ewts-converter#1]
There should probably be some way to convert the "scholar ewts" to Unicode, a few differences:

- `ṅa` -> `nga`
- `ña` -> `nya`
- `źa` -> `zha`
- `śa` -> `sha`
- `ḥa` -> `'a` (or `H`, depends)
- `ṃ` (with dot below) -> `M`
- `m` (with dot above) -> `~M`
- `ā ī ū` -> `A I U`
- `ṛ` -> `r-i`
- `ṝ` -> `r-I`
- `ḷ` -> `l-i`
- `ḷ` (with macron) -> `l-I`
- `-` -> ` `
- handling strange case (`rDo-rje`)
- using `.` instead of `+`
- using `ʹ` or `U+0060` instead of `.`
- etc.

**Comment by xristy** [comment]
Paul Hackett has a converter to Unicode written in java I think but I don't see it anywhere online

**Comment by eroux** [comment]
There's a significant number of works with Cover Titles containing DWTS in the BDRC database. [This one](https://www.tbrc.org/#!rid=W00JR1718) is an interesting example named `Sṅags bcos beʼu bum phyogs bsgrigs /[sgrig pa po, Hum̐-chen daṅ Ñi-zla].`. I'm not sure what the `[` and `]` are supposed to mean, but it exemplifies the use of diacritics on upper cased letters (`Ñ`) and some variants in the diacritics used (`m̐`). Note that a first pass could detect if common DWTS characters are present (`ṅ`, `ñ`, `ś`, etc.) and switch to DWTS mode if it's the case. 

Edit: this title is actually ALA-LC (and marked as such)...
