### ISSUE TITLE
Port to Javascript

### ISSUE THREAD

**Issue by moksamedia** [buda-base/ewts-converter#9]
Howdy. Just FYI, I used JSweet to port this library to Javascript. 

https://github.com/moksamedia/ewts-jsweet

Thanks!

Andrew

**Comment by eroux** [comment]
oh ok, thanks for the notice! Just FYI, https://github.com/buda-base/jsewts is also a port to JS

**Comment by moksamedia** [comment]
Oh, man. Could have saved me some time. Haha. Didn't see that.

**Comment by moksamedia** [comment]
Where are you working that you're translating/studying Tibetan?

**Comment by eroux** [comment]
I'm working for [BDRC](https://bdrc.io), see https://library.bdrc.io/ (actually not the best time right now, we're doing a bit of maintenance!). What about you?

**Comment by moksamedia** [comment]
Oh, cool. I know BDRC well. I'm in Portland and am a student at Maitripa and the DharmaFarm. I'm a student of Bill Magee, Craig Preston, and occasionally Paul Hackett.

**Comment by moksamedia** [comment]
Good luck with the maintenance.
